version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  front:
    build: ./front
    volumes:
      - ./front:/app:cached
      - node_modules:/app/node_modules
    ports:
      - "3003:3000"
      - "24678:24678"
    tty: true
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev"
  api:
    build: ./api
    command: bash -c "rm -f api/tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  node_modules:
